# DEV Environment Configuration
# Backend configuration
backend:
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"

  env:
    DB_NAME: "moviereviews_dev"

# Frontend configuration
frontend:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"

# Model server configuration
model:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"

# Ingress configuration
ingress:
  host: dev-movie.artisantek.in