---
# Secret for backend application database credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  labels:
    app: {{ .Values.backend.name }}
type: Opaque
data:
  # movieuser:moviepass (base64 encoded) - for backend application
  DB_USERNAME: {{ .Values.backend.secret.DB_USERNAME }}
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD }} 